[project]
name = "tetrisml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil>=7.1.3",
    "pufferlib>=3.0.0",
    "wandb>=0.23.0",
]

[dependency-groups]
dev = [
    "basedpyright>=1.33.0",
]
